BEGIN
--ENCABEZADOS
truncate table ZZPRUEBA_ENC;
insert into ZZPRUEBA_ENC
select top 1 
'Z001' as TipoInterfaz,
SUBSTRING(E.SAP_DEN_SOC_FINAN,1,4) as SAP_DEN_SOC_FINAN,
CASE WHEN RIGHT(C.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN 'ZPOS' WHEN RIGHT(C.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN 'YPOS'  ELSE '' END AS ClaseDocumento,
CASE WHEN F.ABONODE_NUMALBARAN = -1 THEN '' ELSE F.ABONODE_NUMSERIE+REPLICATE('0',12-LEN(LTRIM(F.ABONODE_NUMALBARAN)))+LTRIM(F.ABONODE_NUMALBARAN) END AS ReferenciaDocumento,
E.SAP_ORG_VENTAS as OrgVentaSAP,
'0' as MonedaDocumento,
'' as Sector,
E.SAP_OFICINAS_VENTAS as OficinaVentaSAP,
E.SAP_GRUPO_VENDEDOR as GrupoVendedorSAP,
B.CODCLIENTESAP as CodigoClienteSAP, 
A.NOMBRECLIENTE as NombreCliente, 
A.DIRECCION1 as Direccion1, 
A.PROVINCIA as Poblacion, 
A.POBLACION as RegionSAP,
A.TELEFONO1 as Telefono1, 
B.CODCLIENTESAP as Destinatario,
LTRIM(C.NUMSERIE) + REPLICATE('0',12-LEN(C.NUMFAC))+LTRIM(C.NUMFAC) AS NumeroSAP,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as Fecha,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as FechaEntrega,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as FechaPrecio,
'0' as Moneda,
'0' as TipoCambio,
'0' as CondicionPago,
'0' as CondicionExpedicion,
'0' as Texto, 
SUBSTRING (D.MOTIVO_DE_PEDIDO,1,3) as MotivoPedido
from CLIENTES A
inner join CLIENTESCAMPOSLIBRES B
on A.CODCLIENTE = B.CODCLIENTE
inner join ALBVENTACAB    C
on A.CODCLIENTE = C.CODCLIENTE
Inner Join FACTURASVENTACAMPOSLIBRES D
on C.NUMSERIE= D.NUMSERIE
Inner Join SERIESCAMPOSLIBRES E
on C.NUMSERIE = E.SERIE
Inner Join ALBVENTALIN F
on C.NUMSERIE = F.NUMSERIE
where C.NUMSERIE='AAAY' AND C.NUMFAC='1346'; 

--POSICIONES
DECLARE @CANJEO INT 
SET @CANJEO = (SELECT VALOR FROM PARAMETROS WHERE CLAVE = 'FIDEL' AND SUBCLAVE = 'EDTOS')
Truncate table ZZPRUEBADET;
insert into ZZPRUEBADET
select
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN 'ZPOS' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN 'YPOS' ELSE '' END as ClaseDoc, 
LTRIM(A.NUMSERIE) + REPLICATE('0',12-LEN(A.NUMFAC))+LTRIM(A.NUMFAC) AS NumeroSAP,
B.NUMLIN*10 AS Linea,
B.REFERENCIA AS Material, 
CASE WHEN RIGHT (A.NUMSERIEFAC,1)IN('F','H','G','J','K') THEN CAST(B.UNIDADESTOTAL AS INT) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN CAST(B.UNIDADESTOTAL*-1 AS INT) END AS Cantidad, 
ISNULL(F.UNIDADMEDIDA,'') AS UnidadMedida, 
CASE
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') AND F.DPTO IN ('6')  AND B.REFERENCIA NOT IN ('200301') THEN 'TAX' 
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') AND F.DPTO IN ('6')  AND B.REFERENCIA IN ('200301') THEN 'ZFFR'
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DPTO IN ('6')  AND B.REFERENCIA NOT IN ('200301') THEN 'ZTX1' 
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DPTO IN ('6') AND B.REFERENCIA IN ('200301') THEN 'ZTXF' 
WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') AND F.DESCRIPCION  NOT IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'ZPOS'
WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') AND F.DESCRIPCION IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'ZBOL'
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DESCRIPCION NOT IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'YPOS'  
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DESCRIPCION IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'ZBDV'  
ELSE '' END AS TipoPosicion, 
G.CODPOSTAL AS CentroCosto,
G.CENTROCOSTE AS CodigoAlmacen,
'ZPR1' AS CondicionPrecio,
CAST(B.PRECIO AS INT) AS PrecioBase,
CASE WHEN RIGHT (A.NUMSERIEFAC,1)IN('F','H','G','J','K') THEN CAST(B.precio * B.UNIDADESTOTAL AS INT) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y')THEN CAST(B.precio*B.UNIDADESTOTAL*-1 AS INT) END AS PrecioBaseTotal,
'Z024' AS DsctoAuto,
'0' AS Dscto,
'0' AS ValorDscto,
'Z021' AS CondicionSoles,
'0' AS Soles,
'0' AS ValorSoles,
'Z022' AS CondicionDsctoManual,
CASE 
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL)
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL*-1)
ELSE '10' END AS DsctoManual,
CASE 
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL)
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL*-1)
ELSE '0' END AS ValordsctoManual,
'0' AS CondicionBonificacion,
'0' AS PorcentajeBonificacion,
'0' AS ValorBonificacion,
'0' AS CondicionFlete,
'0' AS PorcentajeFlete,
'0' AS ValorFlete,
'0' AS CondicionRecargoM,
'0' AS PorcentajeRecargoM,
'0' AS ValorRecargoM,
'ZIVA' AS CondicionIVA,
CAST(B.IVA AS INT) AS PorcentajeIVA,
CAST(ROUND((B.TOTAL*(B.IVA/100))*B.UNIDADESTOTAL,0) AS INT)AS ValorIVA,
'Z020' AS CondicionProvisionSoles,
CASE WHEN (A.PUNTOSACUM > 0 AND RIGHT(A.NUMSERIE,1) IN  ('F','H','G','J','K')) THEN ROUND((B.TOTALEXPANSION/1000)*@CANJEO,-0) WHEN (A.PUNTOSACUM <> 0 AND RIGHT(A.NUMSERIE,1) IN ('L','M','N','O','Y')) THEN ROUND((B.TOTALEXPANSION/1000)*-1*@CANJEO,-0) ELSE 0*1 END AS ImporteProvisionSoles,
CASE WHEN (A.PUNTOSACUM > 0 AND RIGHT(A.NUMSERIE,1) IN  ('F','H','G','J','K')) THEN ROUND((B.TOTALEXPANSION/1000)*@CANJEO,-0) WHEN (A.PUNTOSACUM <> 0 AND RIGHT(A.NUMSERIE,1) IN ('L','M','N','O','Y')) THEN ROUND((B.TOTALEXPANSION/1000)*-1*@CANJEO,-0) ELSE 0*1 END AS ValorProvisionSoles
FROM ALBVENTACAB A
INNER JOIN ALBVENTALIN B ON A.NUMSERIE = B.NUMSERIE AND A.NUMALBARAN = B.NUMALBARAN AND A.N = B.N
INNER JOIN SERIESCAMPOSLIBRES C ON A.NUMSERIE = C.SERIE
LEFT  JOIN CLIENTESCAMPOSLIBRES D ON A.CODCLIENTE = D.CODCLIENTE 
LEFT  JOIN CLIENTES E ON A.CODCLIENTE = E.CODCLIENTE
INNER JOIN ARTICULOS F ON B.CODARTICULO = F.CODARTICULO
INNER JOIN ALMACEN G ON B.CODALMACEN = G.CODALMACEN
where A.NUMSERIE='AAAY' AND A.NUMFAC='1346'; 
--RECAUDOS
truncate table ZZRECAUDOS;
insert into ZZRECAUDOS
select
'C' as Campo03,
'Z001' as Campo04,
'1000'as Campo05,
'' as Campo06,
(SELECT FORMAT(A.Fecha,N'yyyyMMdd')) as Campo07,
(SELECT FORMAT(A.Fecha,N'yyyyMMdd')) as Campo08,
'COP' as Campo09,
LTRIM(A.NUMSERIE) + REPLICATE('0',12-LEN(A.NUMFAC))+LTRIM(A.NUMFAC) AS Campo10,
'P' as Campo11,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN '40' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN '50'  ELSE '' END as Campo12,
CASE WHEN E.CODTIPOPAGO='1' THEN LEFT(D.CTA_EFECTIVO,10)ELSE F.CUENTACOBRO    END COLLATE Latin1_General_CS_AI as Campo13,
'' as Campo14,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN (SUM(E.IMPORTE)) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('Y','M','N','O','Y') THEN (ABS(SUM(E.IMPORTE)))  ELSE '' END as Campo15,
(CASE WHEN G.RAIZCOBROS IS NULL THEN D.SAP_OFICINAS_VENTAS ELSE G.RAIZCOBROS END)COLLATE Latin1_General_CS_AI as Campo16,
(CASE WHEN G.RAIZPAGOS IS NULL THEN D.SAP_GRUPO_VENDEDOR ELSE G.RAIZPAGOS END)COLLATE Latin1_General_CS_AI as Campo17,
'' as Campo18,
'P' as Campo19,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN '15' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN '05'  ELSE '' END as Campo20,
ISNULL(C.CODCLIENTESAP,'7000000000') as Campo21,
'' as Campo22,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN (SUM(E.IMPORTE)) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('Y','M','N','O','Y') THEN (ABS(SUM(E.IMPORTE)))  ELSE '' END as Campo23,
(CASE WHEN G.RAIZCOBROS IS NULL THEN D.SAP_OFICINAS_VENTAS ELSE G.RAIZCOBROS END) COLLATE Latin1_General_CS_AI as Campo24,
(CASE WHEN G.RAIZPAGOS IS NULL THEN D.SAP_GRUPO_VENDEDOR ELSE G.RAIZPAGOS END) COLLATE Latin1_General_CS_AI as Campo25,
'' as Campo26 
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = C.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on D.SERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE='AAAY' AND A.NUMFAC='1346' 
GROUP BY A.FECHA,A.NUMSERIE,A.NUMFAC,A.NUMSERIEFAC,E.CODTIPOPAGO,D.CTA_EFECTIVO,F.CUENTACOBRO,G.RAIZCOBROS,D.SAP_OFICINAS_VENTAS,G.RAIZPAGOS,D.SAP_GRUPO_VENDEDOR,C.CODCLIENTESAP;

SELECT * FROM  ZZPRUEBA_ENC, ZZPRUEBADET, ZZRECAUDOS FOR XML RAW('IntegracionICG'), ELEMENTS
END

SELECT * FROM ALBVENTACAB WHERE NUMSERIE='BAAY' AND NUMFAC='6579'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BEGIN
--ENCABEZADOS
truncate table ZZPRUEBA_ENC;
insert into ZZPRUEBA_ENC
select top 1 
'Z001' as TipoInterfaz,
SUBSTRING(E.SAP_DEN_SOC_FINAN,1,4) as SAP_DEN_SOC_FINAN,
CASE WHEN RIGHT(C.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN 'ZPOS' WHEN RIGHT(C.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN 'YPOS'  ELSE '' END AS ClaseDocumento,
CASE WHEN F.ABONODE_NUMALBARAN = -1 THEN '' ELSE F.ABONODE_NUMSERIE+REPLICATE('0',12-LEN(LTRIM(F.ABONODE_NUMALBARAN)))+LTRIM(F.ABONODE_NUMALBARAN) END AS ReferenciaDocumento,
E.SAP_ORG_VENTAS as OrgVentaSAP,
'0' as MonedaDocumento,
'' as Sector,
E.SAP_OFICINAS_VENTAS as OficinaVentaSAP,
E.SAP_GRUPO_VENDEDOR as GrupoVendedorSAP,
B.CODCLIENTESAP as CodigoClienteSAP, 
A.NOMBRECLIENTE as NombreCliente, 
A.DIRECCION1 as Direccion1, 
A.PROVINCIA as Poblacion, 
A.POBLACION as RegionSAP,
A.TELEFONO1 as Telefono1, 
B.CODCLIENTESAP as Destinatario,
LTRIM(C.NUMSERIE) + REPLICATE('0',12-LEN(C.NUMFAC))+LTRIM(C.NUMFAC) AS NumeroSAP,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as Fecha,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as FechaEntrega,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as FechaPrecio,
'0' as Moneda,
'0' as TipoCambio,
'0' as CondicionPago,
'0' as CondicionExpedicion,
'0' as Texto, 
SUBSTRING (D.MOTIVO_DE_PEDIDO,1,3) as MotivoPedido
from CLIENTES A
inner join CLIENTESCAMPOSLIBRES B
on A.CODCLIENTE = B.CODCLIENTE
inner join ALBVENTACAB    C
on A.CODCLIENTE = C.CODCLIENTE
Inner Join FACTURASVENTACAMPOSLIBRES D
on C.NUMSERIE= D.NUMSERIE
Inner Join SERIESCAMPOSLIBRES E
on C.NUMSERIE = E.SERIE
Inner Join ALBVENTALIN F
on C.NUMSERIE = F.NUMSERIE
where C.NUMSERIE='AAAY' AND C.NUMFAC='1346'; 

SELECT * FROM ZZPRUEBA_ENC
select * from ALBVENTACAB where NUMSERIEFAC='AAAF' and NUMALBARAN='107306'
select * from ALBVENTALIN where NUMSERIE='AAAY' AND NUMALBARAN='828'
--POSICIONES
DECLARE @CANJEO INT 
SET @CANJEO = (SELECT VALOR FROM PARAMETROS WHERE CLAVE = 'FIDEL' AND SUBCLAVE = 'EDTOS')
Truncate table ZZPRUEBADET;
insert into ZZPRUEBADET
select
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN 'ZPOS' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN 'YPOS' ELSE '' END as ClaseDoc, 
LTRIM(A.NUMSERIE) + REPLICATE('0',12-LEN(A.NUMFAC))+LTRIM(A.NUMFAC) AS NumeroSAP,
B.NUMLIN*10 AS Linea,
B.REFERENCIA AS Material, 
CASE WHEN RIGHT (A.NUMSERIEFAC,1)IN('F','H','G','J','K') THEN CAST(B.UNIDADESTOTAL AS INT) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN CAST(B.UNIDADESTOTAL*-1 AS INT) END AS Cantidad, 
ISNULL(F.UNIDADMEDIDA,'') AS UnidadMedida, 
CASE
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') AND F.DPTO IN ('6')  AND B.REFERENCIA NOT IN ('200301') THEN 'TAX' 
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') AND F.DPTO IN ('6')  AND B.REFERENCIA IN ('200301') THEN 'ZFFR'
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DPTO IN ('6')  AND B.REFERENCIA NOT IN ('200301') THEN 'ZTX1' 
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DPTO IN ('6') AND B.REFERENCIA IN ('200301') THEN 'ZTXF' 
WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') AND F.DESCRIPCION  NOT IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'ZPOS'
WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') AND F.DESCRIPCION IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'ZBOL'
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DESCRIPCION NOT IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'YPOS'  
WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') AND F.DESCRIPCION IN ('IMPUESTO AL CONSUMO BOLSA%') THEN 'ZBDV'  
ELSE '' END AS TipoPosicion, 
G.CODPOSTAL AS CentroCosto,
G.CENTROCOSTE AS CodigoAlmacen,
'ZPR1' AS CondicionPrecio,
CAST(B.PRECIO AS INT) AS PrecioBase,
CASE WHEN RIGHT (A.NUMSERIEFAC,1)IN('F','H','G','J','K') THEN CAST(B.precio * B.UNIDADESTOTAL AS INT) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y')THEN CAST(B.precio*B.UNIDADESTOTAL*-1 AS INT) END AS PrecioBaseTotal,
'Z024' AS DsctoAuto,
'0' AS Dscto,
'0' AS ValorDscto,
'Z021' AS CondicionSoles,
'0' AS Soles,
'0' AS ValorSoles,
'Z022' AS CondicionDsctoManual,
CASE 
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL)
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL*-1)
ELSE '10' END AS DsctoManual,
CASE 
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('F','H','G','J','K') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL)
WHEN (B.DTO > 0) AND RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN ((B.DTO/100)*B.PRECIO*B.UNIDADESTOTAL*-1)
ELSE '0' END AS ValordsctoManual,
'0' AS CondicionBonificacion,
'0' AS PorcentajeBonificacion,
'0' AS ValorBonificacion,
'0' AS CondicionFlete,
'0' AS PorcentajeFlete,
'0' AS ValorFlete,
'0' AS CondicionRecargoM,
'0' AS PorcentajeRecargoM,
'0' AS ValorRecargoM,
'ZIVA' AS CondicionIVA,
CAST(B.IVA AS INT) AS PorcentajeIVA,
CAST(ROUND((B.TOTAL*(B.IVA/100))*B.UNIDADESTOTAL,0) AS INT)AS ValorIVA,
'Z020' AS CondicionProvisionSoles,
CASE WHEN (A.PUNTOSACUM > 0 AND RIGHT(A.NUMSERIE,1) IN  ('F','H','G','J','K')) THEN ROUND((B.TOTALEXPANSION/1000)*@CANJEO,-0) WHEN (A.PUNTOSACUM <> 0 AND RIGHT(A.NUMSERIE,1) IN ('L','M','N','O','Y')) THEN ROUND((B.TOTALEXPANSION/1000)*-1*@CANJEO,-0) ELSE 0*1 END AS ImporteProvisionSoles,
CASE WHEN (A.PUNTOSACUM > 0 AND RIGHT(A.NUMSERIE,1) IN  ('F','H','G','J','K')) THEN ROUND((B.TOTALEXPANSION/1000)*@CANJEO,-0) WHEN (A.PUNTOSACUM <> 0 AND RIGHT(A.NUMSERIE,1) IN ('L','M','N','O','Y')) THEN ROUND((B.TOTALEXPANSION/1000)*-1*@CANJEO,-0) ELSE 0*1 END AS ValorProvisionSoles
FROM ALBVENTACAB A
INNER JOIN ALBVENTALIN B ON A.NUMSERIE = B.NUMSERIE AND A.NUMALBARAN = B.NUMALBARAN AND A.N = B.N
INNER JOIN SERIESCAMPOSLIBRES C ON A.NUMSERIE = C.SERIE
LEFT  JOIN CLIENTESCAMPOSLIBRES D ON A.CODCLIENTE = D.CODCLIENTE 
LEFT  JOIN CLIENTES E ON A.CODCLIENTE = E.CODCLIENTE
INNER JOIN ARTICULOS F ON B.CODARTICULO = F.CODARTICULO
INNER JOIN ALMACEN G ON B.CODALMACEN = G.CODALMACEN
where A.NUMSERIE='AAAY' AND A.NUMFAC='1346'; 

--RECAUDOS
truncate table ZZRECAUDOSXML;
insert into ZZRECAUDOSXML
select
'C' as Campo03,
'Z001' as Campo04,
'1000'as Campo05,
'' as Campo06,
(SELECT FORMAT(A.Fecha,N'yyyyMMdd')) as Campo07,
(SELECT FORMAT(A.Fecha,N'yyyyMMdd')) as Campo08,
'COP' as Campo09,
LTRIM(A.NUMSERIE) + REPLICATE('0',12-LEN(A.NUMFAC))+LTRIM(A.NUMFAC) AS Campo10
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = C.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on D.SERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE='AAAY' AND A.NUMFAC='1346' 
GROUP BY A.FECHA,A.NUMSERIE,A.NUMFAC,A.NUMSERIEFAC,E.CODTIPOPAGO,D.CTA_EFECTIVO,F.CUENTACOBRO,G.RAIZCOBROS,D.SAP_OFICINAS_VENTAS,G.RAIZPAGOS,D.SAP_GRUPO_VENDEDOR,C.CODCLIENTESAP;
--
insert into ZZRECAUDOSXML
select
'P' as Campo03,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN '40' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN '50'  ELSE '' END as Campo04,
CASE WHEN E.CODTIPOPAGO='1' THEN LEFT(D.CTA_EFECTIVO,10)ELSE F.CUENTACOBRO    END COLLATE Latin1_General_CS_AI as Campo05,
'' as Campo06,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN (SUM(E.IMPORTE)) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('Y','M','N','O','Y') THEN (ABS(SUM(E.IMPORTE)))  ELSE '' END as Campo07,
(CASE WHEN G.RAIZCOBROS IS NULL THEN D.SAP_OFICINAS_VENTAS ELSE G.RAIZCOBROS END)COLLATE Latin1_General_CS_AI as Campo08,
(CASE WHEN G.RAIZPAGOS IS NULL THEN D.SAP_GRUPO_VENDEDOR ELSE G.RAIZPAGOS END)COLLATE Latin1_General_CS_AI as Campo09,
'' as Campo010
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = C.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on D.SERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE='AAAY' AND A.NUMFAC='1346' 
GROUP BY A.FECHA,A.NUMSERIE,A.NUMFAC,A.NUMSERIEFAC,E.CODTIPOPAGO,D.CTA_EFECTIVO,F.CUENTACOBRO,G.RAIZCOBROS,D.SAP_OFICINAS_VENTAS,G.RAIZPAGOS,D.SAP_GRUPO_VENDEDOR,C.CODCLIENTESAP;
--
insert into ZZRECAUDOSXML
select
'P' as Campo19,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN '15' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN '05'  ELSE '' END as Campo20,
ISNULL(C.CODCLIENTESAP,'7000000000') as Campo21,
'' as Campo22,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN (SUM(E.IMPORTE)) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('Y','M','N','O','Y') THEN (ABS(SUM(E.IMPORTE)))  ELSE '' END as Campo23,
(CASE WHEN G.RAIZCOBROS IS NULL THEN D.SAP_OFICINAS_VENTAS ELSE G.RAIZCOBROS END) COLLATE Latin1_General_CS_AI as Campo24,
(CASE WHEN G.RAIZPAGOS IS NULL THEN D.SAP_GRUPO_VENDEDOR ELSE G.RAIZPAGOS END) COLLATE Latin1_General_CS_AI as Campo25,
'' as Campo26 
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = C.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on D.SERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE='AAAY' AND A.NUMFAC='1346' 
GROUP BY A.FECHA,A.NUMSERIE,A.NUMFAC,A.NUMSERIEFAC,E.CODTIPOPAGO,D.CTA_EFECTIVO,F.CUENTACOBRO,G.RAIZCOBROS,D.SAP_OFICINAS_VENTAS,G.RAIZPAGOS,D.SAP_GRUPO_VENDEDOR,C.CODCLIENTESAP;
SELECT * FROM  ZZPRUEBA_ENC, ZZPRUEBADET, ZZRECAUDOSXML FOR XML RAW('IntegracionICG'), ELEMENTS
END

Z

select * from zztabla_errores
insert into zztabla_errores values ('No existe entrega para el pedido','Productos sin inventario en SAP','inventarios','juanito perez','juanitoperunga@gmail.com')