DECLARE 
@numserie NVARCHAR(MAX),
@numfac NVARCHAR(MAX)
--
SET @numserie='AAAF'
SET @numfac='178203'

--ENCABEZADOS
truncate table ZZPRUEBA_ENC;
insert into ZZPRUEBA_ENC
select top 1
'Z001' as TipoInterfaz,
SUBSTRING(E.SAP_DEN_SOC_FINAN,1,4) as SAP_DEN_SOC_FINAN,
CASE WHEN RIGHT(C.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN 'ZPOS' WHEN RIGHT(C.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN 'YPOS'  ELSE '' END AS ClaseDocumento,
CASE WHEN F.ABONODE_NUMALBARAN = -1 THEN '' ELSE G.NUMSERIEFAC+REPLICATE('0',12-LEN(LTRIM((G.NUMFAC))))+LTRIM(G.NUMFAC) END AS ReferenciaDocumento,
E.SAP_ORG_VENTAS as OrgVentaSAP,
'0' as MonedaDocumento,
'' as Sector,
CASE WHEN I.RAIZCOBROS IS NOT NULL THEN I.RAIZCOBROS ELSE E.SAP_OFICINAS_VENTAS  END AS OficinaVentaSAP,
CASE WHEN I.RAIZPAGOS IS NOT NULL THEN I.RAIZPAGOS ELSE E.SAP_GRUPO_VENDEDOR END AS GrupoVendedorSAP,
ISNULL(B.CODCLIENTESAP,'7000000000') as CodigoClienteSAP, 
CASE WHEN B.CODCLIENTESAP IS NULL THEN (SELECT NOMBRECLIENTE FROM CLIENTES WHERE CODCLIENTE='7000627') ELSE A.NOMBRECLIENTE END AS NombreCliente, 
CASE WHEN B.CODCLIENTESAP IS NULL THEN (SELECT DIRECCION1 FROM CLIENTES WHERE CODCLIENTE='7000627') ELSE A.DIRECCION1 END AS Direccion1, 
CASE WHEN B.CODCLIENTESAP IS NULL THEN (SELECT PROVINCIA FROM CLIENTES WHERE CODCLIENTE='7000627') ELSE A.PROVINCIA END AS Poblacion, 
CASE WHEN B.CODCLIENTESAP IS NULL THEN (SELECT POBLACION FROM CLIENTES WHERE CODCLIENTE='7000627') ELSE A.POBLACION END AS RegionSAP,
CASE WHEN B.CODCLIENTESAP IS NULL THEN (SELECT TELEFONO1 FROM CLIENTES WHERE CODCLIENTE='7000627') ELSE  A.TELEFONO1 END AS Telefono1, 
ISNULL(B.CODCLIENTESAP,'7000000000') as Destinatario,
LTRIM(C.NUMSERIE) + REPLICATE('0',12-LEN(C.NUMFAC))+LTRIM(C.NUMFAC) AS NumeroSAP,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as Fecha,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as FechaEntrega,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) as FechaPrecio,
'0' as Moneda,
'0' as TipoCambio,
'0' as CondicionPago,
'0' as CondicionExpedicion,
'0' as Texto, 
SUBSTRING (D.MOTIVO_DE_PEDIDO,1,3) as MotivoPedido
from CLIENTES A
inner join CLIENTESCAMPOSLIBRES B
on A.CODCLIENTE = B.CODCLIENTE
inner join ALBVENTACAB    C
on A.CODCLIENTE = C.CODCLIENTE
Inner Join FACTURASVENTACAMPOSLIBRES D
on C.NUMSERIE= D.NUMSERIE
Inner Join SERIESCAMPOSLIBRES E
on C.NUMSERIE = E.SERIE
Inner Join ALBVENTALIN F
on C.NUMSERIE = F.NUMSERIE AND C.NUMALBARAN = F.NUMALBARAN
Left Join ITG_ENC2 G
on C.NUMSERIE = G.NUMSERIE_ENC AND C.NUMALBARAN = G.NUMALBARAN_ENC
Inner Join TESORERIA H
on C.NUMSERIE = H.SERIE AND C.NUMFAC = H.NUMERO
Inner Join TIPOSPAGO I
on H.CODTIPOPAGO = i.CODTIPOPAGO
where C.NUMSERIE=@numserie AND C.NUMFAC=@numfac;
SELECT * FROM ZZPRUEBA_ENC for XML raw('DataVentasEnc'), elements

