DECLARE 
@numserie NVARCHAR(MAX),
@numfac NVARCHAR(MAX)
--
SET @numserie='AAAF'
SET @numfac='178203'

--ENCABEZADOS
TRUNCATE TABLE ZZPRUEBA_ENC;
INSERT INTO ZZPRUEBA_ENC
SELECT TOP 1
'Z001' AS TipoInterfaz,
SUBSTRING(E.SAP_DEN_SOC_FINAN,1,4) AS SAP_DEN_SOC_FINAN,
CASE WHEN RIGHT(C.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN 'ZPOS' WHEN RIGHT(C.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN 'YPOS'  ELSE '' END AS ClaseDocumento,
CASE WHEN F.ABONODE_NUMALBARAN = -1 THEN '' ELSE G.NUMSERIEFAC+REPLICATE('0',12-LEN(LTRIM((G.NUMFAC))))+LTRIM(G.NUMFAC) END AS ReferenciaDocumento,
E.SAP_ORG_VENTAS AS OrgVentaSAP,
'0' AS MonedaDocumento,
'' AS Sector,
CASE WHEN I.RAIZCOBROS IS NOT NULL THEN I.RAIZCOBROS ELSE E.SAP_OFICINAS_VENTAS  END AS OficinaVentaSAP,
CASE WHEN I.RAIZPAGOS IS NOT NULL THEN I.RAIZPAGOS ELSE E.SAP_GRUPO_VENDEDOR END AS GrupoVendedorSAP,
ISNULL(B.CODCLIENTESAP,'') AS CodigoClienteSAP, 
ISNULL(A.NOMBRECLIENTE,'') AS NombreCliente, 
ISNULL(A.DIRECCION1,'') AS Direccion1, 
ISNULL(A.PROVINCIA,'') AS Poblacion, 
ISNULL(A.POBLACION,'') AS RegionSAP,
ISNULL(A.TELEFONO1,'') AS Telefono1, 
ISNULL(B.CODCLIENTESAP,'') AS Destinatario,
LTRIM(C.NUMSERIE) + REPLICATE('0',12-LEN(C.NUMFAC))+LTRIM(C.NUMFAC) AS NumeroSAP,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) AS Fecha,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) AS FechaEntrega,
(SELECT FORMAT(C.Fecha,N'yyyyMMdd')) AS FechaPrecio,
'0' AS Moneda,
'0' AS TipoCambio,
'0' AS CondicionPago,
'0' AS CondicionExpedicion,
'0' AS Texto, 
SUBSTRING (D.MOTIVO_DE_PEDIDO,1,3) AS MotivoPedido
FROM [ICGTIERRAGRO2017].DBO.CLIENTES A
INNER JOIN [ICGTIERRAGRO2017].DBO.CLIENTESCAMPOSLIBRES B
ON A.CODCLIENTE = B.CODCLIENTE
INNER JOIN [ICGTIERRAGRO2017].DBO.ALBVENTACAB    C
ON A.CODCLIENTE = C.CODCLIENTE
INNER JOIN [ICGTIERRAGRO2017].DBO.FACTURASVENTACAMPOSLIBRES D
ON C.NUMSERIE= D.NUMSERIE
INNER JOIN [ICGTIERRAGRO2017].DBO.SERIESCAMPOSLIBRES E
ON C.NUMSERIE = E.SERIE
INNER JOIN [ICGTIERRAGRO2017].DBO.ALBVENTALIN F
ON C.NUMSERIE = F.NUMSERIE AND C.NUMALBARAN = F.NUMALBARAN
LEFT JOIN ITG_ENC2 G
ON C.NUMSERIE = G.NUMSERIE_ENC AND C.NUMALBARAN = G.NUMALBARAN_ENC
INNER JOIN [ICGTIERRAGRO2017].DBO.TESORERIA H
ON C.NUMSERIE = H.SERIE AND C.NUMFAC = H.NUMERO
INNER JOIN [ICGTIERRAGRO2017].DBO.TIPOSPAGO I
ON H.CODTIPOPAGO = i.CODTIPOPAGO
WHERE C.NUMSERIE=@numserie AND C.NUMFAC=@numfac;
SELECT * FROM ZZPRUEBA_ENC FOR XML RAW('DataVentasEnc'), ELEMENTS

