DECLARE 
@numserie NVARCHAR(MAX),
@numfac NVARCHAR(MAX)
--
SET @numserie='AAAF'
SET @numfac='178203'

--RECAUDOS
truncate table ZZRECAUDOSXML;
--Recaudos CABECERA
insert into ZZRECAUDOSXML
select top 1
'C' as Campo03,
'Z001' as Campo04,
'1000'as Campo05,
'' as Campo06,
(SELECT FORMAT(A.Fecha,N'yyyyMMdd')) as Campo07,
(SELECT FORMAT(A.Fecha,N'yyyyMMdd')) as Campo08,
'COP' as Campo09,
LTRIM(A.NUMSERIE) + REPLICATE('0',12-LEN(A.NUMFAC))+LTRIM(A.NUMFAC) AS Campo10
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = C.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on D.SERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE=@numserie AND A.NUMFAC=@numfac AND E.CODTIPOPAGO NOT IN ('-1');
--RecaudosMedioDePago
Insert into ZZRECAUDOSXML
Select  
'P' as Campo03,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN '40' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN '50'  ELSE '' END as Campo04,
CASE WHEN E.CODTIPOPAGO='1' THEN LEFT(D.CTA_EFECTIVO,10)ELSE F.CUENTACOBRO	END COLLATE Latin1_General_CS_AI as Campo05,
'' as Campo06,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN (E.IMPORTE) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('Y','M','N','O','Y') THEN (ABS(E.IMPORTE))  ELSE '' END as Campo07,
(CASE WHEN G.RAIZCOBROS IS NULL THEN D.SAP_OFICINAS_VENTAS ELSE G.RAIZCOBROS END)COLLATE Latin1_General_CS_AI as Campo08,
(CASE WHEN G.RAIZPAGOS IS NULL THEN D.SAP_GRUPO_VENDEDOR ELSE G.RAIZPAGOS END)COLLATE Latin1_General_CS_AI as Campo09,
'' as Campo10
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = c.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on A.NUMSERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE=@numserie AND A.NUMFAC=@numfac AND E.CODTIPOPAGO NOT IN ('-1') 
GROUP BY A.NUMSERIEFAC,E.CODTIPOPAGO,D.CTA_EFECTIVO,F.CUENTACOBRO,E.IMPORTE,G.RAIZCOBROS,D.SAP_OFICINAS_VENTAS,G.RAIZPAGOS,D.SAP_GRUPO_VENDEDOR;
--RecaudosDatosCliente
Insert into ZZRECAUDOSXML
Select TOP 1
'P' as Campo03,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN '15' WHEN RIGHT(A.NUMSERIEFAC,1) IN ('L','M','N','O','Y') THEN '05'  ELSE '' END as Campo04,
ISNULL(C.CODCLIENTESAP,'7000000000') as Campo05,
'' as Campo06,
CASE WHEN RIGHT(A.NUMSERIEFAC,1) IN  ('F','H','G','J','K') THEN SUM(SUM(DISTINCT E.IMPORTE))OVER(ORDER BY E.IMPORTE DESC) WHEN RIGHT(A.NUMSERIEFAC,1) IN ('Y','M','N','O','Y') THEN (ABS(E.IMPORTE)) ELSE '' END as Campo07,
(CASE WHEN G.RAIZCOBROS IS NULL THEN D.SAP_OFICINAS_VENTAS ELSE G.RAIZCOBROS END) COLLATE Latin1_General_CS_AI as Campo08,
(CASE WHEN G.RAIZPAGOS IS NULL THEN D.SAP_GRUPO_VENDEDOR ELSE G.RAIZPAGOS END) COLLATE Latin1_General_CS_AI as Campo09,
'' as Campo10
From ALBVENTACAB A
inner join CLIENTES B
on A.CODCLIENTE = B.CODCLIENTE
inner Join CLIENTESCAMPOSLIBRES C
on B.CODCLIENTE = c.CODCLIENTE
inner Join SERIESCAMPOSLIBRES D
on A.NUMSERIE = D.SERIE
inner Join TESORERIA E
on A.NUMSERIE = E.SERIE AND A.NUMFAC = E.NUMERO
inner Join VENCIMFPAGO F
on E.CODTIPOPAGO = F.CODTIPOPAGO
inner Join TIPOSPAGO G
on E.CODTIPOPAGO = G.CODTIPOPAGO
inner Join ALBVENTALIN H
on A.NUMSERIE = H.NUMSERIE AND A.NUMALBARAN = H.NUMALBARAN
where A.NUMSERIE=@numserie AND A.NUMFAC=@numfac AND E.CODTIPOPAGO NOT IN ('-1')  
GROUP BY A.NUMSERIEFAC, C.CODCLIENTESAP, E.IMPORTE, G.RAIZCOBROS, D.SAP_OFICINAS_VENTAS, G.RAIZPAGOS, D.SAP_GRUPO_VENDEDOR
ORDER BY CAMPO07 DESC
--XML
SELECT * FROM ZZRECAUDOSXML
FOR XML RAW('DataRecaudo'), ELEMENTS
